"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import { SCHOOL } from "@/lib/messages";
import { useState } from "react";

export default function SchoolSettingsPage() {
  const { session, ready } = useAuth();
  const router = useRouter();
  const [policy, setPolicy] = useState<"admin_all" | "split">(
    "split",
  );
  const [logoName, setLogoName] = useState("riverside-crest.svg");
  const [escrowReady, setEscrowReady] = useState(true);

  useEffect(() => {
    if (ready && session && session.role !== "school") {
      router.replace("/dashboard");
    }
  }, [ready, session, router]);

  if (!session || session.role !== "school") return null;

  return (
    <div className="w-full fade-in">
      <header className="mb-6">
        <h1 className="font-display text-3xl font-semibold tracking-tight">
          {SCHOOL.settingsTitle}
        </h1>
        <p className="mt-1 text-[var(--ink-muted)]">{SCHOOL.settingsSubtitle}</p>
      </header>

      <div className="grid gap-5">
        <section className="surface p-5">
          <h2 className="font-semibold">{SCHOOL.branding}</h2>
          <p className="mt-1 text-sm text-[var(--ink-muted)]">
            Logo applies to lesson exports generated by this school&apos;s
            teachers.
          </p>
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <div className="flex h-16 w-16 items-center justify-center rounded-[var(--radius-sm)] bg-[var(--brand-soft)] font-display text-xl font-semibold text-[var(--brand-deep)]">
              RM
            </div>
            <div>
              <p className="text-sm font-medium">{logoName}</p>
              <button
                type="button"
                className="btn btn-secondary mt-2"
                onClick={() => setLogoName("riverside-crest-v2.svg")}
              >
                Upload logo (demo)
              </button>
            </div>
          </div>
        </section>

        <section className="surface p-5">
          <h2 className="font-semibold">{SCHOOL.policy}</h2>
          <p className="mt-1 text-sm text-[var(--ink-muted)]">
            Controls who can approve promotions into School KB vs Platform KB.
          </p>
          <div className="mt-4 grid gap-3">
            <label className="flex cursor-pointer gap-3 rounded-[var(--radius-sm)] border border-[var(--line)] p-3">
              <input
                type="radio"
                name="policy"
                checked={policy === "admin_all"}
                onChange={() => setPolicy("admin_all")}
              />
              <span>
                <span className="block font-semibold">
                  School admin approves everything
                </span>
                <span className="text-sm text-[var(--ink-muted)]">
                  Including requests aimed at Platform KB.
                </span>
              </span>
            </label>
            <label className="flex cursor-pointer gap-3 rounded-[var(--radius-sm)] border border-[var(--line)] p-3">
              <input
                type="radio"
                name="policy"
                checked={policy === "split"}
                onChange={() => setPolicy("split")}
              />
              <span>
                <span className="block font-semibold">
                  Split approval (recommended)
                </span>
                <span className="text-sm text-[var(--ink-muted)]">
                  School admin → School KB. Platform owner → Platform KB.
                </span>
              </span>
            </label>
          </div>
        </section>

        <section className="surface p-5">
          <h2 className="font-semibold">{SCHOOL.escrow}</h2>
          <p className="mt-1 text-sm text-[var(--ink-muted)]">
            {SCHOOL.escrowDesc}
          </p>
          <div className="mt-4 rounded-[var(--radius-sm)] bg-[var(--bg)] p-4 text-sm">
            <p>
              Status:{" "}
              <span className="font-semibold text-[var(--ok)]">
                {escrowReady ? "Admin share held" : "Awaiting teacher setup"}
              </span>
            </p>
            <p className="mt-2 text-[var(--ink-muted)]">
              Active teacher backups with escrow: 12
            </p>
            <button
              type="button"
              className="btn btn-secondary mt-3"
              onClick={() => setEscrowReady(true)}
            >
              Rotate admin key share (demo)
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
